version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres-retro
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-retro_logs}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-user} -d $${POSTGRES_DB:-retro_logs}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - retro_net

networks:
  retro_net:
    driver: bridge

volumes:
  db-data: 